"""Identidades inequivocamente sintéticas compartilhadas pelos testes."""

SYNTHETIC_PATIENT_ALPHA = "PACIENTE ÁRVORE EXEMPLO"
SYNTHETIC_PATIENT_ALPHA_ASCII = "PACIENTE ARVORE EXEMPLO"
SYNTHETIC_PATIENT_ALPHA_DICOM = "PACIENTE^ÁRVORE EXEMPLO"
SYNTHETIC_PATIENT_BETA = "PACIENTE BETA EXEMPLO"
SYNTHETIC_PATIENT_GAMMA = "PACIENTE GAMA EXEMPLO"
SYNTHETIC_PATIENT_ID = "SYNTHETIC-PATIENT-001"
SYNTHETIC_REQUEST_ID = "99999999"
SYNTHETIC_REQUEST_ID_BETA = "99999998"
SYNTHETIC_REQUEST_ID_GAMMA = "99999997"
SYNTHETIC_INTERNAL_REQUEST_ID = "99999992"
SYNTHETIC_SEQUENTIAL_ID = "999991"
SYNTHETIC_CLINIC_ID = "999992"
SYNTHETIC_NUMERIC_PATIENT_ID = "900001"
SYNTHETIC_STUDY_DATE = "20990102"
SYNTHETIC_BIRTH_DATE = "20900102"
SYNTHETIC_EPOCH_MILLISECONDS = "4070997000000"
SYNTHETIC_MESSAGE_ID = "synthetic-message-alpha"
SYNTHETIC_TIMESTAMP = "20990102120000"
SYNTHETIC_TIMESTAMP_BETA = "20990103130000"
SYNTHETIC_TIMESTAMP_GAMMA = "20990102124500"
SYNTHETIC_CPF_PLACEHOLDER = "SYNTHETIC-CPF-NOT-A-NUMBER"

SYNTHETIC_PERSON_EXACT = "PESSOA TESTE ALFA"
SYNTHETIC_PERSON_EXACT_TITLE = "Pessoa Teste Alfa"
SYNTHETIC_PERSON_ACCENTED = "PESSOA ÁRVORE TESTE"
SYNTHETIC_PERSON_ACCENTED_ASCII = "PESSOA ARVORE TESTE"
SYNTHETIC_PERSON_DICOM = "TESTE^PESSOA^ÁRVORE"
SYNTHETIC_PERSON_DICOM_ASCII = "TESTE PESSOA ARVORE"
SYNTHETIC_PERSON_AMBIGUOUS = "PESSOA TESTE COMPOSTA"
SYNTHETIC_PERSON_AMBIGUOUS_ALT = "PESSOA TESTE DA COMPOSTA"
SYNTHETIC_PERSON_UNRELATED = "PESSOA CONTROLE ÔMEGA"
SYNTHETIC_PERSON_SIMILAR = "PESSOA TESTE ALF"
SYNTHETIC_PERSON_LOW_SCORE = "INDIVÍDUO CONTROLE DELTA"
SYNTHETIC_ARCHIVE_NAME = f"{SYNTHETIC_PERSON_ACCENTED}_{SYNTHETIC_STUDY_DATE}.zip"
SYNTHETIC_RAR_NAME = (
    f"PESSOA INEQUIVOCAMENTE SINTÉTICA COM NOME EXTENSO PARA TESTE_"
    f"{SYNTHETIC_STUDY_DATE}120000.rar"
)


def synthetic_patient_name(sequence: int) -> str:
    """Gera nome humano claramente artificial para cenários adicionais."""
    return f"PACIENTE SINTÉTICO {sequence:02d}"


def synthetic_request_id(sequence: int) -> str:
    """Gera identificador numérico reservado exclusivamente aos testes."""
    return f"99{sequence:06d}"
